"""Regenerate Fig 1 (causal graph) and Fig 2 (retrieval pipeline) - N09.

Both figures are produced by this single committed script, never hand-drawn and never
hand-typed. Fig 1's node positions, labels, and every cosine-similarity annotation are
computed from one small scenario generated by the REAL benchmark generator
(``tcmfbench.generator.generate``, the same one N01-N06 use), dumped to the committed
``figures/fig1_scenario.json`` and then re-loaded from that JSON file before drawing - so the
rendered labels are provably the committed data, not values that happened to still be in
memory. Fig 2 is a schematic of ``api.memory.tcmf.TCMFRetriever.retrieve()``'s actual pipeline
stages; ``tcmfbench.test_n09_figures`` checks its box text against phrases lifted verbatim from
that module's and ``causal_graph.py``'s source, so the diagram cannot silently drift from the
real code.

Run:
    python research/tcmf_paper/figures/make_figures.py --out research/tcmf_paper/figures
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

_FIGURES_DIR = Path(__file__).resolve().parent
_TCMF_PAPER_DIR = _FIGURES_DIR.parent
_REPO_ROOT = _TCMF_PAPER_DIR.parent.parent
for p in (str(_TCMF_PAPER_DIR), str(_REPO_ROOT)):
    if p not in sys.path:
        sys.path.insert(0, p)

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch

from tcmfbench.generator import GenConfig, generate

# Okabe-Ito colorblind-safe palette.
COLOR_CAUSAL = "#0072B2"      # blue - causal-chain events / their witness memories
COLOR_DISTRACTOR = "#E69F00"  # orange - semantically-near, causally-off-path distractors
COLOR_CRISIS = "#D55E00"      # vermillion - the crisis node itself
COLOR_EDGE = "#333333"
COLOR_SIM_ANNOT = "#555555"

FIG1_SEED = 42
FIG1_SCENARIO_ID = "fig1_illustrative"

# Small, deliberately reduced-cardinality config (3-event chain, 2 distractors, no noise) so
# the figure stays legible at 3.3in column width. Generated by the real generator - not a
# hand-drawn cartoon - just with a smaller n than the eval configs use.
FIG1_CONFIG = GenConfig(
    dim=64, n_topics=24, chain_len=3, n_distractors=2, n_noise=0,
    witnesses_per_ancestor=1,
)


def _cosine(a: list[float], b: list[float]) -> float:
    va, vb = np.asarray(a, dtype=np.float64), np.asarray(b, dtype=np.float64)
    denom = float(np.linalg.norm(va) * np.linalg.norm(vb))
    return float(np.dot(va, vb) / denom) if denom > 0 else 0.0


def build_fig1_scenario_json() -> dict:
    """Generate the illustrative scenario and shape it into the committed JSON schema."""
    sc = generate(FIG1_SCENARIO_ID, FIG1_CONFIG, seed=FIG1_SEED)

    events = [
        {
            "id": ev.id, "text": ev.text, "tick": ev.tick, "topic": ev.topic,
            "kind": ev.kind, "embedding": [round(x, 6) for x in ev.embedding],
        }
        for ev in sc.events
    ]
    # Assign display ids in generation order (post-shuffle, deterministic given FIG1_SEED) -
    # these memories are never inserted into a real MemoryStream for a figure-only scenario,
    # so MemorySpec.id is still "".
    memories = []
    for idx, m in enumerate(sc.memories):
        memories.append({
            "id": f"mem{idx}", "text": m.text, "tick": m.tick, "topic": m.topic,
            "label": m.label, "importance": m.importance,
            "embedding": [round(x, 6) for x in m.embedding],
        })

    return {
        "generator": "tcmfbench.generator.generate",
        "scenario_id": FIG1_SCENARIO_ID,
        "seed": FIG1_SEED,
        "config": {
            "dim": FIG1_CONFIG.dim, "n_topics": FIG1_CONFIG.n_topics,
            "chain_len": FIG1_CONFIG.chain_len, "n_distractors": FIG1_CONFIG.n_distractors,
            "n_noise": FIG1_CONFIG.n_noise,
            "witnesses_per_ancestor": FIG1_CONFIG.witnesses_per_ancestor,
        },
        "events": events,
        "edges": [list(e) for e in sc.edges],
        "crisis_event_id": sc.crisis_event_id,
        "memories": memories,
    }


def _kind_label(kind: str) -> str:
    return {"root_cause": "root cause", "decision": "decision", "crisis": "crisis"}.get(kind, kind)


def draw_fig1(data: dict, out_stub: Path) -> None:
    """Fig 1: the causal graph - ancestor chain + root cause vs. semantically-near
    distractors sitting off the causal path. Every position and cosine value below is
    derived from ``data``, i.e. the committed JSON, not typed in by hand."""
    events = {e["id"]: e for e in data["events"]}
    edges = [tuple(e) for e in data["edges"]]
    crisis_id = data["crisis_event_id"]
    memories = data["memories"]

    # order events root -> ... -> crisis by walking the edge chain
    incoming = {b for _, b in edges}
    order = [eid for eid in events if eid not in incoming]
    nxt = dict(edges)
    while order[-1] in nxt:
        order.append(nxt[order[-1]])

    # Data units are inches - figsize below must match the xlim/ylim spans used here, so
    # every text placement can be reasoned about directly in physical size.
    n_events = len(order)
    step = 1.0
    ex = {eid: 0.5 + i * step for i, eid in enumerate(order)}
    ey = {eid: 1.85 for eid in order}

    fig_w, fig_h = 3.3, 4.0
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    ax.set_xlim(0, fig_w)
    ax.set_ylim(0, fig_h)
    ax.axis("off")

    # causal-chain arrows
    for a, b in edges:
        ax.annotate(
            "", xy=(ex[b] - 0.20, ey[b]), xytext=(ex[a] + 0.20, ey[a]),
            arrowprops=dict(arrowstyle="-|>", color=COLOR_EDGE, lw=1.3, shrinkA=0, shrinkB=0),
        )

    # event nodes
    for eid in order:
        ev = events[eid]
        color = COLOR_CRISIS if eid == crisis_id else COLOR_CAUSAL
        ax.scatter([ex[eid]], [ey[eid]], s=170, color=color, zorder=3,
                   edgecolors="black", linewidths=0.6)
        ax.text(ex[eid], ey[eid] + 0.40, _kind_label(ev["kind"]),
                ha="center", va="bottom", fontsize=8.0, fontweight="bold")
        ax.text(ex[eid], ey[eid] - 0.40, f"topic {ev['topic']}",
                ha="center", va="top", fontsize=8.0, color="#444444")

    # witness memories under their causal-ancestor event, drawn from `memories`, not invented
    ancestor_ids = order[:-1]
    root_id = order[0]
    witness_by_event: dict[str, list[dict]] = {eid: [] for eid in ancestor_ids}
    distractors: list[dict] = []
    for m in memories:
        if m["label"] in ("gold_root", "gold_chain"):
            for eid in ancestor_ids:
                if events[eid]["topic"] == m["topic"]:
                    witness_by_event[eid].append(m)
        elif m["label"] == "distractor":
            distractors.append(m)

    for eid, ws in witness_by_event.items():
        for wi, m in enumerate(ws):
            wx, wy = ex[eid], ey[eid] - 0.95 - 0.62 * wi
            ax.scatter([wx], [wy], s=70, color=COLOR_CAUSAL, marker="s", zorder=3,
                       edgecolors="black", linewidths=0.4)
            ax.plot([ex[eid], wx], [ey[eid] - 0.40, wy + 0.12], "--", color=COLOR_CAUSAL,
                    lw=0.7, alpha=0.6, zorder=1)
            ax.text(wx + 0.16, wy, "witness", ha="left", va="center",
                    fontsize=8.0, color=COLOR_CAUSAL)

    # distractor cluster - semantically near the crisis, causally disconnected (no edge drawn),
    # stacked ABOVE the crisis's own kind label so it never competes for the same horizontal band
    crisis_x = ex[crisis_id]
    dist_y0 = ey[crisis_id] + 0.85
    for di, m in enumerate(distractors):
        dy = dist_y0 + 0.30 * di
        ax.scatter([crisis_x], [dy], s=70, color=COLOR_DISTRACTOR, marker="^", zorder=3,
                   edgecolors="black", linewidths=0.4)
    if distractors:
        ax.text(crisis_x, dist_y0 + 0.30 * (len(distractors) - 1) + 0.20,
                "distractors\n(off-path)", ha="center", va="bottom",
                fontsize=8.0, color=COLOR_DISTRACTOR)

    # ground the "semantically near / far" claim in real numbers, computed from data
    root_witnesses = witness_by_event.get(root_id, [])
    crisis_emb = events[crisis_id]["embedding"]
    if root_witnesses and distractors:
        cos_root = _cosine(root_witnesses[0]["embedding"], crisis_emb)
        cos_dist = _cosine(distractors[0]["embedding"], crisis_emb)
        mid_x = fig_w / 2
        ax.text(mid_x, 0.55, f"cos(root-cause witness, crisis) = {cos_root:.2f}",
                ha="center", va="bottom", fontsize=8.0, color=COLOR_SIM_ANNOT)
        ax.text(mid_x, 0.20, f"cos(distractor, crisis) = {cos_dist:.2f}",
                ha="center", va="bottom", fontsize=8.0, color=COLOR_SIM_ANNOT)

    fig.tight_layout(pad=0.25)
    fig.savefig(out_stub.with_suffix(".pdf"))
    fig.savefig(out_stub.with_suffix(".png"), dpi=220)
    plt.close(fig)


def _box(ax, xy, w, h, text, color, fontsize=8.0):
    x, y = xy
    box = FancyBboxPatch(
        (x - w / 2, y - h / 2), w, h, boxstyle="round,pad=0.02,rounding_size=0.06",
        linewidth=1.0, edgecolor="black", facecolor=color, alpha=0.9, zorder=2,
    )
    ax.add_patch(box)
    ax.text(x, y, text, ha="center", va="center", fontsize=fontsize, zorder=3)


def _arrow(ax, p0, p1):
    ax.add_patch(FancyArrowPatch(
        p0, p1, arrowstyle="-|>", mutation_scale=9, color=COLOR_EDGE, lw=1.1,
        shrinkA=2, shrinkB=2, zorder=1,
    ))


# Stage text for Fig 2. Short for legibility at column width, but each phrase is a
# substring-preserving paraphrase of real source text - test_n09_figures.py checks the
# underlying formulas (SOURCE_GROUNDING below) appear verbatim in api/memory/tcmf.py and
# api/memory/causal_graph.py, so the diagram cannot silently drift from the shipped retriever.
FIG2_STAGES = {
    "episodic_input": "Episodic\nmemories",
    "episodic_score": "relevance x\nrecency x\nimportance",
    "crisis_input": "Crisis\nevent",
    "bfs": "BFS backward\n(depth <= 4)",
    "ancestors": "{ancestor_id:\ndepth}",
    "causal_boost": "max over causal\nancestors,\ncos >= threshold",
    "fusion": "minmax(episodic)\n+ lambda x\ncausal_boost",
    "output": "Ranked\nmemories",
}

# Literal substrings pulled from the real source files - what test_n09_figures.py checks
# FIG2_STAGES's claims against.
SOURCE_GROUNDING = {
    "api/memory/causal_graph.py": ["BFS backward from event_id", "{ancestor_id: depth}"],
    "api/memory/tcmf.py": [
        "causal_boost(m) = max over causal ancestors",
        "minmax(episodic) + lambda * causal_boost",
    ],
    "api/memory/stream.py": ["w_rel * relevance + w_rec * recency + w_imp * importance"],
}


def _stack_down(top_y: float, heights: list[float], gap: float) -> list[float]:
    """Return center-y for each box, stacked top to bottom with a fixed edge-to-edge gap."""
    centers = []
    y = top_y
    for h in heights:
        y -= h / 2
        centers.append(y)
        y -= h / 2 + gap
    return centers


def draw_fig2(out_stub: Path) -> None:
    """Fig 2: TCMFRetriever.retrieve()'s pipeline, mirroring its real step order (steps 1-5
    in api/memory/tcmf.py). Two narrow columns (causal stream on the left, episodic stream on
    the right) stack vertically rather than spreading horizontally, so every box stays wide
    enough for an 8pt-legible label within the 3.3in single-column width. Both streams
    converge into one fusion box, then one ranked output.

    Data units are inches (figsize matches xlim/ylim exactly); box centers are computed by
    ``_stack_down`` from explicit heights and a fixed gap, so edges cannot silently overlap."""
    fig_w = 3.3
    x_causal, x_epi = 0.85, 2.45
    w_col = 1.5
    gap = 0.4
    top_y = 6.0

    causal_heights = [0.65, 0.8, 0.8, 1.15]  # crisis, bfs, ancestors, causal_boost
    causal_y = _stack_down(top_y, causal_heights, gap)
    crisis_xy, bfs_xy, anc_xy, boost_xy = ((x_causal, y) for y in causal_y)

    epi_heights = [0.65, 0.95]  # episodic memories, episodic score
    epi_y = _stack_down(top_y, epi_heights, gap)
    epi_in_xy, epi_score_xy = ((x_epi, y) for y in epi_y)

    stream_bottom = min(causal_y[-1] - causal_heights[-1] / 2, epi_y[-1] - epi_heights[-1] / 2)
    fusion_h, output_h = 1.35, 0.55
    fusion_y, output_y = _stack_down(stream_bottom - gap, [fusion_h, output_h], gap)
    fusion_xy = ((x_causal + x_epi) / 2, fusion_y)
    output_xy = ((x_causal + x_epi) / 2, output_y)

    fig_h = top_y + 0.6 - (output_y - output_h / 2)
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    ax.set_xlim(0, fig_w)
    ax.set_ylim(output_y - output_h / 2 - 0.15, top_y + 0.55)
    ax.axis("off")

    _box(ax, crisis_xy, w_col, causal_heights[0], FIG2_STAGES["crisis_input"], "#F6D8C2")
    _box(ax, bfs_xy, w_col, causal_heights[1], FIG2_STAGES["bfs"], COLOR_DISTRACTOR)
    _box(ax, anc_xy, w_col, causal_heights[2], FIG2_STAGES["ancestors"], COLOR_DISTRACTOR)
    _box(ax, boost_xy, w_col, causal_heights[3], FIG2_STAGES["causal_boost"], COLOR_DISTRACTOR)

    _box(ax, epi_in_xy, w_col, epi_heights[0], FIG2_STAGES["episodic_input"], "#CCE5F5")
    _box(ax, epi_score_xy, w_col, epi_heights[1], FIG2_STAGES["episodic_score"], COLOR_CAUSAL)

    _box(ax, fusion_xy, 2.0, fusion_h, FIG2_STAGES["fusion"], "#777777")
    _box(ax, output_xy, 1.7, output_h, FIG2_STAGES["output"], "#999999")

    def _v_arrow(x, y_top_box, h_top, y_bot_box, h_bot):
        _arrow(ax, (x, y_top_box - h_top / 2), (x, y_bot_box + h_bot / 2))

    # causal stream, top to bottom
    for (y0, h0), (y1, h1) in zip(
        zip(causal_y, causal_heights), zip(causal_y[1:], causal_heights[1:])
    ):
        _v_arrow(x_causal, y0, h0, y1, h1)
    # episodic stream, top to bottom
    _v_arrow(x_epi, epi_y[0], epi_heights[0], epi_y[1], epi_heights[1])
    # both streams converge into fusion
    _arrow(ax, (x_causal + 0.35, boost_xy[1] - causal_heights[-1] / 2 + 0.1),
           (fusion_xy[0] - 0.5, fusion_xy[1] + fusion_h / 2 - 0.15))
    _arrow(ax, (x_epi - 0.35, epi_score_xy[1] - epi_heights[-1] / 2 + 0.1),
           (fusion_xy[0] + 0.5, fusion_xy[1] + fusion_h / 2 - 0.15))
    # fusion -> output
    _v_arrow(fusion_xy[0], fusion_xy[1], fusion_h, output_xy[1], output_h)

    fig.tight_layout(pad=0.25)
    fig.savefig(out_stub.with_suffix(".pdf"))
    fig.savefig(out_stub.with_suffix(".png"), dpi=220)
    plt.close(fig)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=str, default=str(_FIGURES_DIR))
    args = ap.parse_args()
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    data = build_fig1_scenario_json()
    scenario_path = out_dir / "fig1_scenario.json"
    scenario_path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")
    # Re-load before drawing: Fig 1 is provably drawn from the committed file, not from
    # whatever is still sitting in the `data` variable above.
    reloaded = json.loads(scenario_path.read_text())
    draw_fig1(reloaded, out_dir / "fig1_causal_graph")
    print(f"wrote {scenario_path}")
    print(f"wrote {out_dir / 'fig1_causal_graph.pdf'} / .png")

    draw_fig2(out_dir / "fig2_pipeline")
    print(f"wrote {out_dir / 'fig2_pipeline.pdf'} / .png")


if __name__ == "__main__":
    main()
