"""Regenerate all six paper figures (N09-N11).

Every figure is produced by this single committed script, never hand-drawn and never
hand-typed. Fig 1's node positions, labels, and every cosine-similarity annotation are computed
from one small scenario generated by the REAL benchmark generator
(``tcmfbench.generator.generate``, the same one N01-N06 use), dumped to the committed
``figures/fig1_scenario.json`` and then re-loaded from that JSON file before drawing - so the
rendered labels are provably the committed data, not values that happened to still be in memory.
Fig 2 is a schematic of ``api.memory.tcmf.TCMFRetriever.retrieve()``'s actual pipeline stages;
``tcmfbench.test_n09_figures`` checks its box text against phrases lifted verbatim from that
module's and ``causal_graph.py``'s source, so the diagram cannot silently drift from the real
code. Fig 3 plots ``theory.py``'s affine margin-vs-lambda mechanism on real scenario pairs. Fig 4
reads the committed lambda sweep (``results_lambda_sweep/``). Fig 5 reads the committed dropout
(``results_mixed/``) and spurious-edge (``results_spurious/``) curves. Fig 6 reads the committed
decision-quality tier (``results_decision/``).

Run:
    python research/tcmf_paper/figures/make_figures.py --out research/tcmf_paper/figures
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

import numpy as np

_FIGURES_DIR = Path(__file__).resolve().parent
_TCMF_PAPER_DIR = _FIGURES_DIR.parent
_REPO_ROOT = _TCMF_PAPER_DIR.parent.parent
for p in (str(_TCMF_PAPER_DIR), str(_REPO_ROOT)):
    if p not in sys.path:
        sys.path.insert(0, p)

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch

from tcmfbench.generator import GenConfig, generate
from tcmfbench.mixed import MixedConfig, generate_mixed
from tcmfbench import methods as M
from tcmfbench import theory as T
from tcmfbench.stats import wilson_ci

# Okabe-Ito colorblind-safe palette.
COLOR_CAUSAL = "#0072B2"      # blue - causal-chain events / their witness memories / additive
COLOR_DISTRACTOR = "#E69F00"  # orange - semantically-near, causally-off-path distractors
COLOR_CRISIS = "#D55E00"      # vermillion - the crisis node itself
COLOR_EDGE = "#333333"
COLOR_SIM_ANNOT = "#555555"
COLOR_MULT = "#CC79A7"        # reddish-purple - multiplicative fusion (fig4/fig6)

# One Okabe-Ito colorblind-safe color per method, reused across figures so a method means the
# same color everywhere in the paper.
METHOD_COLORS = {
    "semantic_rag": "#999999",   # gray - the semantic-only floor
    "episodic":     "#56B4E9",   # sky blue
    "causal_only":  "#009E73",   # green
    "graph_ppr":    COLOR_DISTRACTOR,  # orange
    "tcmf_mult":    COLOR_MULT,  # reddish-purple - the broken fusion operator
    "tcmf_add":     COLOR_CAUSAL,  # blue
    "tcmf_shipped": "#000000",   # black - the paper's shipped method
    "tcmf_rrf":     "#F0E442",   # yellow
}

FIG1_SEED = 42
FIG1_SCENARIO_ID = "fig1_illustrative"

# Small, deliberately reduced-cardinality config (3-event chain, 2 distractors, no noise) so
# the figure stays legible at 3.3in column width. Generated by the real generator - not a
# hand-drawn cartoon - just with a smaller n than the eval configs use.
FIG1_CONFIG = GenConfig(
    dim=64, n_topics=24, chain_len=3, n_distractors=2, n_noise=0,
    witnesses_per_ancestor=1,
)


def _cosine(a: list[float], b: list[float]) -> float:
    va, vb = np.asarray(a, dtype=np.float64), np.asarray(b, dtype=np.float64)
    denom = float(np.linalg.norm(va) * np.linalg.norm(vb))
    return float(np.dot(va, vb) / denom) if denom > 0 else 0.0


def build_fig1_scenario_json() -> dict:
    """Generate the illustrative scenario and shape it into the committed JSON schema."""
    sc = generate(FIG1_SCENARIO_ID, FIG1_CONFIG, seed=FIG1_SEED)

    events = [
        {
            "id": ev.id, "text": ev.text, "tick": ev.tick, "topic": ev.topic,
            "kind": ev.kind, "embedding": [round(x, 6) for x in ev.embedding],
        }
        for ev in sc.events
    ]
    # Assign display ids in generation order (post-shuffle, deterministic given FIG1_SEED) -
    # these memories are never inserted into a real MemoryStream for a figure-only scenario,
    # so MemorySpec.id is still "".
    memories = []
    for idx, m in enumerate(sc.memories):
        memories.append({
            "id": f"mem{idx}", "text": m.text, "tick": m.tick, "topic": m.topic,
            "label": m.label, "importance": m.importance,
            "embedding": [round(x, 6) for x in m.embedding],
        })

    return {
        "generator": "tcmfbench.generator.generate",
        "scenario_id": FIG1_SCENARIO_ID,
        "seed": FIG1_SEED,
        "config": {
            "dim": FIG1_CONFIG.dim, "n_topics": FIG1_CONFIG.n_topics,
            "chain_len": FIG1_CONFIG.chain_len, "n_distractors": FIG1_CONFIG.n_distractors,
            "n_noise": FIG1_CONFIG.n_noise,
            "witnesses_per_ancestor": FIG1_CONFIG.witnesses_per_ancestor,
        },
        "events": events,
        "edges": [list(e) for e in sc.edges],
        "crisis_event_id": sc.crisis_event_id,
        "memories": memories,
    }


def _kind_label(kind: str) -> str:
    return {"root_cause": "root cause", "decision": "decision", "crisis": "crisis"}.get(kind, kind)


def draw_fig1(data: dict, out_stub: Path) -> None:
    """Fig 1: the causal graph - ancestor chain + root cause vs. semantically-near
    distractors sitting off the causal path. Every position and cosine value below is
    derived from ``data``, i.e. the committed JSON, not typed in by hand."""
    events = {e["id"]: e for e in data["events"]}
    edges = [tuple(e) for e in data["edges"]]
    crisis_id = data["crisis_event_id"]
    memories = data["memories"]

    # order events root -> ... -> crisis by walking the edge chain
    incoming = {b for _, b in edges}
    order = [eid for eid in events if eid not in incoming]
    nxt = dict(edges)
    while order[-1] in nxt:
        order.append(nxt[order[-1]])

    # Data units are inches - figsize below must match the xlim/ylim spans used here, so
    # every text placement can be reasoned about directly in physical size.
    n_events = len(order)
    step = 1.0
    ex = {eid: 0.5 + i * step for i, eid in enumerate(order)}
    ey = {eid: 1.85 for eid in order}

    fig_w, fig_h = 3.3, 4.0
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    ax.set_xlim(0, fig_w)
    ax.set_ylim(0, fig_h)
    ax.axis("off")

    # causal-chain arrows
    for a, b in edges:
        ax.annotate(
            "", xy=(ex[b] - 0.20, ey[b]), xytext=(ex[a] + 0.20, ey[a]),
            arrowprops=dict(arrowstyle="-|>", color=COLOR_EDGE, lw=1.3, shrinkA=0, shrinkB=0),
        )

    # event nodes
    for eid in order:
        ev = events[eid]
        color = COLOR_CRISIS if eid == crisis_id else COLOR_CAUSAL
        ax.scatter([ex[eid]], [ey[eid]], s=170, color=color, zorder=3,
                   edgecolors="black", linewidths=0.6)
        ax.text(ex[eid], ey[eid] + 0.40, _kind_label(ev["kind"]),
                ha="center", va="bottom", fontsize=8.0, fontweight="bold")
        ax.text(ex[eid], ey[eid] - 0.40, f"topic {ev['topic']}",
                ha="center", va="top", fontsize=8.0, color="#444444")

    # witness memories under their causal-ancestor event, drawn from `memories`, not invented
    ancestor_ids = order[:-1]
    root_id = order[0]
    witness_by_event: dict[str, list[dict]] = {eid: [] for eid in ancestor_ids}
    distractors: list[dict] = []
    for m in memories:
        if m["label"] in ("gold_root", "gold_chain"):
            for eid in ancestor_ids:
                if events[eid]["topic"] == m["topic"]:
                    witness_by_event[eid].append(m)
        elif m["label"] == "distractor":
            distractors.append(m)

    for eid, ws in witness_by_event.items():
        for wi, m in enumerate(ws):
            wx, wy = ex[eid], ey[eid] - 0.95 - 0.62 * wi
            ax.scatter([wx], [wy], s=70, color=COLOR_CAUSAL, marker="s", zorder=3,
                       edgecolors="black", linewidths=0.4)
            ax.plot([ex[eid], wx], [ey[eid] - 0.40, wy + 0.12], "--", color=COLOR_CAUSAL,
                    lw=0.7, alpha=0.6, zorder=1)
            ax.text(wx + 0.16, wy, "witness", ha="left", va="center",
                    fontsize=8.0, color=COLOR_CAUSAL)

    # distractor cluster - semantically near the crisis, causally disconnected (no edge drawn),
    # stacked ABOVE the crisis's own kind label so it never competes for the same horizontal band
    crisis_x = ex[crisis_id]
    dist_y0 = ey[crisis_id] + 0.85
    for di, m in enumerate(distractors):
        dy = dist_y0 + 0.30 * di
        ax.scatter([crisis_x], [dy], s=70, color=COLOR_DISTRACTOR, marker="^", zorder=3,
                   edgecolors="black", linewidths=0.4)
    if distractors:
        ax.text(crisis_x, dist_y0 + 0.30 * (len(distractors) - 1) + 0.20,
                "distractors\n(off-path)", ha="center", va="bottom",
                fontsize=8.0, color=COLOR_DISTRACTOR)

    # ground the "semantically near / far" claim in real numbers, computed from data
    root_witnesses = witness_by_event.get(root_id, [])
    crisis_emb = events[crisis_id]["embedding"]
    if root_witnesses and distractors:
        cos_root = _cosine(root_witnesses[0]["embedding"], crisis_emb)
        cos_dist = _cosine(distractors[0]["embedding"], crisis_emb)
        mid_x = fig_w / 2
        ax.text(mid_x, 0.55, f"cos(root-cause witness, crisis) = {cos_root:.2f}",
                ha="center", va="bottom", fontsize=8.0, color=COLOR_SIM_ANNOT)
        ax.text(mid_x, 0.20, f"cos(distractor, crisis) = {cos_dist:.2f}",
                ha="center", va="bottom", fontsize=8.0, color=COLOR_SIM_ANNOT)

    fig.tight_layout(pad=0.25)
    fig.savefig(out_stub.with_suffix(".pdf"))
    fig.savefig(out_stub.with_suffix(".png"), dpi=220)
    plt.close(fig)


def _box(ax, xy, w, h, text, color, fontsize=8.0):
    x, y = xy
    box = FancyBboxPatch(
        (x - w / 2, y - h / 2), w, h, boxstyle="round,pad=0.02,rounding_size=0.06",
        linewidth=1.0, edgecolor="black", facecolor=color, alpha=0.9, zorder=2,
    )
    ax.add_patch(box)
    ax.text(x, y, text, ha="center", va="center", fontsize=fontsize, zorder=3)


def _arrow(ax, p0, p1):
    ax.add_patch(FancyArrowPatch(
        p0, p1, arrowstyle="-|>", mutation_scale=9, color=COLOR_EDGE, lw=1.1,
        shrinkA=2, shrinkB=2, zorder=1,
    ))


# Stage text for Fig 2. Short for legibility at column width, but each phrase is a
# substring-preserving paraphrase of real source text - test_n09_figures.py checks the
# underlying formulas (SOURCE_GROUNDING below) appear verbatim in api/memory/tcmf.py and
# api/memory/causal_graph.py, so the diagram cannot silently drift from the shipped retriever.
FIG2_STAGES = {
    "episodic_input": "Episodic\nmemories",
    "episodic_score": "relevance x\nrecency x\nimportance",
    "crisis_input": "Crisis\nevent",
    "bfs": "BFS backward\n(depth <= 4)",
    "ancestors": "{ancestor_id:\ndepth}",
    "causal_boost": "max over causal\nancestors,\ncos >= threshold",
    "fusion": "minmax(episodic)\n+ lambda x\ncausal_boost",
    "output": "Ranked\nmemories",
}

# Literal substrings pulled from the real source files - what test_n09_figures.py checks
# FIG2_STAGES's claims against.
SOURCE_GROUNDING = {
    "api/memory/causal_graph.py": ["BFS backward from event_id", "{ancestor_id: depth}"],
    "api/memory/tcmf.py": [
        "causal_boost(m) = max over causal ancestors",
        "minmax(episodic) + lambda * causal_boost",
    ],
    "api/memory/stream.py": ["w_rel * relevance + w_rec * recency + w_imp * importance"],
}


def _stack_down(top_y: float, heights: list[float], gap: float) -> list[float]:
    """Return center-y for each box, stacked top to bottom with a fixed edge-to-edge gap."""
    centers = []
    y = top_y
    for h in heights:
        y -= h / 2
        centers.append(y)
        y -= h / 2 + gap
    return centers


def draw_fig2(out_stub: Path) -> None:
    """Fig 2: TCMFRetriever.retrieve()'s pipeline, mirroring its real step order (steps 1-5
    in api/memory/tcmf.py). Two narrow columns (causal stream on the left, episodic stream on
    the right) stack vertically rather than spreading horizontally, so every box stays wide
    enough for an 8pt-legible label within the 3.3in single-column width. Both streams
    converge into one fusion box, then one ranked output.

    Data units are inches (figsize matches xlim/ylim exactly); box centers are computed by
    ``_stack_down`` from explicit heights and a fixed gap, so edges cannot silently overlap."""
    fig_w = 3.3
    x_causal, x_epi = 0.85, 2.45
    w_col = 1.5
    gap = 0.4
    top_y = 6.0

    causal_heights = [0.65, 0.8, 0.8, 1.15]  # crisis, bfs, ancestors, causal_boost
    causal_y = _stack_down(top_y, causal_heights, gap)
    crisis_xy, bfs_xy, anc_xy, boost_xy = ((x_causal, y) for y in causal_y)

    epi_heights = [0.65, 0.95]  # episodic memories, episodic score
    epi_y = _stack_down(top_y, epi_heights, gap)
    epi_in_xy, epi_score_xy = ((x_epi, y) for y in epi_y)

    stream_bottom = min(causal_y[-1] - causal_heights[-1] / 2, epi_y[-1] - epi_heights[-1] / 2)
    fusion_h, output_h = 1.35, 0.55
    fusion_y, output_y = _stack_down(stream_bottom - gap, [fusion_h, output_h], gap)
    fusion_xy = ((x_causal + x_epi) / 2, fusion_y)
    output_xy = ((x_causal + x_epi) / 2, output_y)

    fig_h = top_y + 0.6 - (output_y - output_h / 2)
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    ax.set_xlim(0, fig_w)
    ax.set_ylim(output_y - output_h / 2 - 0.15, top_y + 0.55)
    ax.axis("off")

    _box(ax, crisis_xy, w_col, causal_heights[0], FIG2_STAGES["crisis_input"], "#F6D8C2")
    _box(ax, bfs_xy, w_col, causal_heights[1], FIG2_STAGES["bfs"], COLOR_DISTRACTOR)
    _box(ax, anc_xy, w_col, causal_heights[2], FIG2_STAGES["ancestors"], COLOR_DISTRACTOR)
    _box(ax, boost_xy, w_col, causal_heights[3], FIG2_STAGES["causal_boost"], COLOR_DISTRACTOR)

    _box(ax, epi_in_xy, w_col, epi_heights[0], FIG2_STAGES["episodic_input"], "#CCE5F5")
    _box(ax, epi_score_xy, w_col, epi_heights[1], FIG2_STAGES["episodic_score"], COLOR_CAUSAL)

    _box(ax, fusion_xy, 2.0, fusion_h, FIG2_STAGES["fusion"], "#777777")
    _box(ax, output_xy, 1.7, output_h, FIG2_STAGES["output"], "#999999")

    def _v_arrow(x, y_top_box, h_top, y_bot_box, h_bot):
        _arrow(ax, (x, y_top_box - h_top / 2), (x, y_bot_box + h_bot / 2))

    # causal stream, top to bottom
    for (y0, h0), (y1, h1) in zip(
        zip(causal_y, causal_heights), zip(causal_y[1:], causal_heights[1:])
    ):
        _v_arrow(x_causal, y0, h0, y1, h1)
    # episodic stream, top to bottom
    _v_arrow(x_epi, epi_y[0], epi_heights[0], epi_y[1], epi_heights[1])
    # both streams converge into fusion
    _arrow(ax, (x_causal + 0.35, boost_xy[1] - causal_heights[-1] / 2 + 0.1),
           (fusion_xy[0] - 0.5, fusion_xy[1] + fusion_h / 2 - 0.15))
    _arrow(ax, (x_epi - 0.35, epi_score_xy[1] - epi_heights[-1] / 2 + 0.1),
           (fusion_xy[0] + 0.5, fusion_xy[1] + fusion_h / 2 - 0.15))
    # fusion -> output
    _v_arrow(fusion_xy[0], fusion_xy[1], fusion_h, output_xy[1], output_h)

    fig.tight_layout(pad=0.25)
    fig.savefig(out_stub.with_suffix(".pdf"))
    fig.savefig(out_stub.with_suffix(".png"), dpi=220)
    plt.close(fig)


# --------------------------------------------------------------------------------- Fig 3 (N10)
#
# One root-vs-hardest-distractor pair per seed, across the same 10 seeds ``run_theory.py``
# sweeps - so this figure's spread is the exact one already cited in main.tex (a 3.0x swing,
# 3.11-9.26), not one scenario's own distractors, which are too similar to each other to show
# cross-scenario spread on their own.

FIG3_SEEDS = tuple(range(1, 11))
FIG3_CONFIG = MixedConfig(n_distractors=20, n_noise=55)  # matches run_theory.py's defaults
FIG3_BOOST_KW = dict(threshold=0.45, clean=True, favor_root=False)  # matches run_theory.py
FIG3_LAM_MAX = 10.0


def build_fig3_pairs_json() -> dict:
    """One root-vs-worst-distractor pair per seed (the ``mult_required_lambda``-defining
    competitor), across the same 10 seeds ``run_theory.py`` sweeps - shaped into the committed
    JSON schema. Same generator, config and boost kwargs, so this figure's numbers are directly
    cross-checkable against ``results_theory.json``'s rows, not invented."""
    pairs = []
    for seed in FIG3_SEEDS:
        mat = M.materialize(generate_mixed(f"fig3_s{seed}", FIG3_CONFIG, seed=seed))
        e = M._episodic_scores(mat)
        ehat = M._minmax(e)
        b = M._causal_boosts(mat, **FIG3_BOOST_KW)
        root = mat.root_id
        distractors = sorted(M.distractor_ids(mat))

        # The competitor that drives mult_required_lambda for this seed: the one with the
        # largest (or unreachable) multiplicative crossover, i.e. the hardest to promote.
        def _mult_key(j: str) -> float:
            xc = T.mult_crossover_lambda(e[root], b[root], e[j], b[j])
            return math.inf if xc is None else xc
        worst_j = max(distractors, key=_mult_key)

        pairs.append({
            "seed": seed, "distractor_id": worst_j,
            "e_root": e[root], "e_j": e[worst_j],
            "ehat_root": ehat[root], "ehat_j": ehat[worst_j],
            "b_root": b[root], "b_j": b[worst_j],
            "mult_promotable": T.mult_promotable(e[root], b[root], e[worst_j], b[worst_j]),
            "mult_crossover_lambda": T.mult_crossover_lambda(
                e[root], b[root], e[worst_j], b[worst_j]),
            "additive_sufficient_lambda": T.additive_sufficient_lambda(
                ehat[root], b[root], ehat[worst_j], b[worst_j]),
            # the episodic-independent bound (Corollary 2.1) for this seed's full distractor set
            "additive_uniform_bound_lambda": T.additive_required_lambda(
                b, root, set(distractors)),
        })

    return {
        "generator": "tcmfbench.mixed.generate_mixed",
        "seeds": list(FIG3_SEEDS),
        "config": {"n_distractors": FIG3_CONFIG.n_distractors, "n_noise": FIG3_CONFIG.n_noise},
        "boost_kw": FIG3_BOOST_KW,
        "pairs": pairs,
    }


def draw_fig3(data: dict, out_stub: Path) -> None:
    """Fig 3: the fusion-operator theory as a picture (N10). Both operators' pairwise margins
    are affine in lambda (``theory.py``); this plots margin vs lambda for the root cause against
    its hardest-to-promote distractor, one pair per seed across the same 10 seeds
    ``run_theory.py`` sweeps. Multiplicative crossings scatter across lambda because each pair's
    crossing point depends on that scenario's own episodic scores (the exact 3.0x swing already
    reported in the text); additive crossings all sit left of that seed's lambda-independent
    bound. Every plotted value is read from ``data``, the committed JSON - not hand-drawn
    geometry."""
    pairs = data["pairs"]
    lam = np.linspace(0.0, FIG3_LAM_MAX, 400)
    n_unreachable = sum(1 for p in pairs if not p["mult_promotable"])

    # A fixed y-range sized to the PROMOTABLE pairs, so the rare (1/10 seeds here, ~1/200
    # pairs in the full sweep) unreachable case - whose margin diverges - clips off the top
    # instead of flattening every other line into an unreadable clump.
    MULT_YLIM = (-2.2, 3.0)
    ADD_YLIM = (-1.5, 3.0)

    fig, (ax_mult, ax_add) = plt.subplots(1, 2, figsize=(3.3, 2.2))

    for p in pairs:
        m_margin = ((p["e_root"] - p["e_j"])
                    + lam * (p["e_root"] * p["b_root"] - p["e_j"] * p["b_j"]))
        color = COLOR_CAUSAL if p["mult_promotable"] else COLOR_DISTRACTOR
        ax_mult.plot(lam, m_margin, color=color, lw=0.7, alpha=0.6)
        xc = p["mult_crossover_lambda"]
        if xc is not None and xc <= FIG3_LAM_MAX:
            ax_mult.scatter([xc], [0.0], s=8, color=color, zorder=3)
    ax_mult.axhline(0.0, color=COLOR_EDGE, lw=0.6)
    ax_mult.set_ylim(*MULT_YLIM)
    if n_unreachable:
        ax_mult.annotate(f"{n_unreachable}/{len(pairs)} seeds:\nno $\\lambda$ works",
                          xy=(FIG3_LAM_MAX * 0.55, MULT_YLIM[0] + 0.15),
                          fontsize=5.6, color=COLOR_DISTRACTOR)
    ax_mult.set_title("multiplicative", fontsize=7.5)
    ax_mult.set_xlabel(r"$\lambda$", fontsize=7.5)
    ax_mult.set_ylabel("margin (root - distractor)", fontsize=6.3)
    ax_mult.tick_params(labelsize=6)

    max_bound = 0.0
    for p in pairs:
        a_margin = (p["ehat_root"] - p["ehat_j"]) + lam * (p["b_root"] - p["b_j"])
        ax_add.plot(lam, a_margin, color=COLOR_CAUSAL, lw=0.7, alpha=0.6)
        xc = p["additive_sufficient_lambda"]
        if xc is not None and xc <= FIG3_LAM_MAX:
            ax_add.scatter([xc], [0.0], s=8, color=COLOR_CAUSAL, zorder=3)
        bound = p["additive_uniform_bound_lambda"]
        if math.isfinite(bound):
            max_bound = max(max_bound, bound)
    ax_add.set_ylim(*ADD_YLIM)
    if max_bound and max_bound <= FIG3_LAM_MAX:
        ax_add.axvline(max_bound, color=COLOR_CRISIS, lw=1.0, ls="--", zorder=2)
        ax_add.text(max_bound + 0.15, ADD_YLIM[1] * 0.85,
                     f"worst-seed\nbound={max_bound:.2f}", fontsize=5.6, color=COLOR_CRISIS)
    ax_add.axhline(0.0, color=COLOR_EDGE, lw=0.6)
    ax_add.set_title("additive", fontsize=7.5)
    ax_add.set_xlabel(r"$\lambda$", fontsize=7.5)
    ax_add.tick_params(labelsize=6)

    fig.tight_layout(pad=0.3, w_pad=1.1)
    fig.savefig(out_stub.with_suffix(".pdf"))
    fig.savefig(out_stub.with_suffix(".png"), dpi=220)
    plt.close(fig)


# --------------------------------------------------------------------------------- Fig 4 (N10)

def draw_fig4(sweep: dict, out_stub: Path) -> None:
    """Recall@5 vs lambda, both operators, one axis, N02 bootstrap CI bands
    (``results_lambda_sweep/``, produced by ``tcmfbench.run_lambda_sweep``). The multiplicative
    curve's flat low-lambda region and the marked N03 tune-selected point (lambda=2.4) are both
    drawn from that committed, sanity-checked JSON."""
    lambdas = sweep["multiplicative"]["lambda"]
    fig, ax = plt.subplots(figsize=(3.3, 2.6))

    for key, color, label in (("multiplicative", COLOR_MULT, "multiplicative"),
                              ("additive", COLOR_CAUSAL, "additive")):
        curve = sweep[key]
        mean = np.array(curve["mean"])
        lo = np.array(curve["ci_lo"])
        hi = np.array(curve["ci_hi"])
        ax.plot(lambdas, mean, color=color, lw=1.3, marker="o", markersize=2.5, label=label,
               zorder=3)
        ax.fill_between(lambdas, lo, hi, color=color, alpha=0.18, zorder=1, linewidth=0)

    # flat low-lambda region for the multiplicative curve, shaded to make it visually obvious
    ax.axvspan(0, 1.0, color=COLOR_MULT, alpha=0.08, zorder=0)
    ax.text(0.5, 0.03, "flat", ha="center", va="bottom", fontsize=6.5, color=COLOR_MULT,
           transform=ax.get_xaxis_transform())

    tuned = sweep["tuned_mult_lambda_recall5"]
    ax.scatter([sweep["tuned_mult_lambda"]], [tuned["mean"]], s=32, color=COLOR_MULT,
              edgecolors="black", linewidths=0.6, zorder=4)
    ax.annotate(
        f"tuned $\\lambda$={sweep['tuned_mult_lambda']:g}\nrecall@5={tuned['mean']:.2f}",
        xy=(sweep["tuned_mult_lambda"], tuned["mean"]),
        xytext=(sweep["tuned_mult_lambda"] + 1.2, tuned["mean"] - 0.22),
        fontsize=6.5, color=COLOR_MULT,
        arrowprops=dict(arrowstyle="-", color=COLOR_MULT, lw=0.6),
    )

    ax.set_xlabel(r"$\lambda$", fontsize=8.0)
    ax.set_ylabel("recall@5", fontsize=8.0)
    ax.set_ylim(-0.02, 1.05)
    ax.tick_params(labelsize=7.0)
    ax.legend(loc="upper left", fontsize=7.0, frameon=False)
    fig.tight_layout(pad=0.25)
    fig.savefig(out_stub.with_suffix(".pdf"))
    fig.savefig(out_stub.with_suffix(".png"), dpi=220)
    plt.close(fig)


# --------------------------------------------------------------------------------- Fig 5 (N11)

_FIG5_METHODS = ["semantic_rag", "causal_only", "tcmf_add"]
_FIG5_COLORS = {"semantic_rag": METHOD_COLORS["semantic_rag"],
                 "causal_only": METHOD_COLORS["causal_only"], "tcmf_add": COLOR_CAUSAL}
_FIG5_LABELS = {"semantic_rag": "semantic (floor)", "causal_only": "causal-only",
                 "tcmf_add": "tcmf-add"}


def draw_fig5(results_mixed: dict, results_spurious: dict, out_stub: Path) -> None:
    """Fig 5: graceful degradation under (a) causal-edge dropout (Table tab:dropout's own
    small-pool, single-seed curve - the exact numbers already published, no CI available at
    that vintage) and (b) N04's spurious-edge rate (``results_spurious.json``'s realistic-pool,
    5-seed curve, which does have CI). The two panels are deliberately NOT put on the same pool
    size: a realistic-pool rerun of the dropout sweep exists (``results_mixed_scale``'s own
    ``dropout_curve``, N01-scale) and shows ``tcmf_add`` falling below the semantic floor at
    high dropout, which contradicts F7's small-pool claim and is not yet reconciled in the text
    - plotting it here without that reconciliation would silently overwrite a published claim,
    so panel (a) stays anchored to what F7 actually reports. ``semantic_rag`` never touches the
    causal graph, so it is drawn as the floor every other method should converge toward in
    panel (a)."""
    fig, (ax_drop, ax_spur) = plt.subplots(1, 2, figsize=(3.3, 2.1), sharey=True)

    drop_rates = [0.0, 0.25, 0.5, 0.75, 1.0]
    dc = results_mixed["dropout_curve"]
    for m in _FIG5_METHODS:
        xs = np.array(drop_rates)
        means = np.array([dc[str(r)][m] for r in drop_rates])
        ls = "--" if m == "semantic_rag" else "-"
        ax_drop.plot(xs, means, color=_FIG5_COLORS[m], lw=1.2, ls=ls, marker="o", ms=2.5,
                     label=_FIG5_LABELS[m])
    ax_drop.set_title("edge dropout\n(small pool, single run)", fontsize=6.8)
    ax_drop.tick_params(labelsize=6)
    ax_drop.set_ylim(-0.02, 1.05)
    ax_drop.set_xlabel("fraction dropped", fontsize=6.3)
    ax_drop.set_ylabel("recall@10", fontsize=7)

    spur_rates = results_spurious["spurious_rates"]
    curve = results_spurious["curve"]
    for m in _FIG5_METHODS:
        xs = np.array(spur_rates, dtype=float)
        means = np.array([curve[str(r)][m]["recall@10"]["mean"] for r in spur_rates])
        los = np.array([curve[str(r)][m]["recall@10"]["ci_lo"] for r in spur_rates])
        his = np.array([curve[str(r)][m]["recall@10"]["ci_hi"] for r in spur_rates])
        ls = "--" if m == "semantic_rag" else "-"
        ax_spur.fill_between(xs, los, his, color=_FIG5_COLORS[m], alpha=0.18, linewidth=0)
        ax_spur.plot(xs, means, color=_FIG5_COLORS[m], lw=1.2, ls=ls, marker="o", ms=2.5,
                     label=_FIG5_LABELS[m])
    ax_spur.set_title("spurious edges\n(realistic pool, 5-seed 95% CI)", fontsize=6.8)
    ax_spur.tick_params(labelsize=6)
    ax_spur.set_xlabel("spurious rate", fontsize=6.3)
    ax_spur.legend(fontsize=5.6, loc="lower left", frameon=False)

    fig.tight_layout(pad=0.3, w_pad=1.1)
    fig.savefig(out_stub.with_suffix(".pdf"))
    fig.savefig(out_stub.with_suffix(".png"), dpi=220)
    plt.close(fig)


# --------------------------------------------------------------------------------- Fig 6 (N11)
#
# results_decision/results_decision.json stores only the aggregate (mean, std, n) per method -
# not the per-scenario 0/1 correctness array - so there is nothing to bootstrap over directly.
# decision_acc IS exactly k/n for some integer k (a mean of binary outcomes), so k is recovered
# exactly from the committed mean and n, and a closed-form Wilson score interval
# (tcmfbench.stats.wilson_ci, unit-tested against Newcombe 1998's published table in
# test_stats.py) gives a proper 95% CI from (k, n) alone - no resampling, no reconstruction of a
# fake per-scenario ordering, no reuse of the LLM cache required.

def build_fig6_data() -> dict:
    """Recompute Wilson CIs for every method's and control's decision_acc from the committed
    ``results_decision/results_decision.json``. Every number here is read from that file or
    derived from it by ``wilson_ci`` - nothing hand-typed."""
    src_path = _TCMF_PAPER_DIR / "results_decision" / "results_decision.json"
    src = json.loads(src_path.read_text())
    n = src["n"]

    def _row(mean: float) -> dict:
        k = mean * n
        k_round = round(k)
        assert abs(k - k_round) < 1e-6, f"decision_acc mean {mean} * n={n} is not integer k"
        p, lo, hi = wilson_ci(k_round, n)
        return {"mean": p, "ci_lo": lo, "ci_hi": hi, "k": k_round, "n": n}

    return {
        "source": "results_decision/results_decision.json",
        "ci_method": "wilson_score_95pct",
        "n": n,
        "methods": {name: _row(v["decision_acc"]["mean"])
                    for name, v in src["methods"].items()},
        "controls": {name: _row(v["decision_acc"]["mean"])
                     for name, v in src["controls"].items()},
    }


FIG6_ORDER = ["semantic_rag", "episodic", "causal_only", "graph_ppr",
              "tcmf_mult", "tcmf_add", "tcmf_shipped", "tcmf_rrf"]


def draw_fig6(data: dict, out_stub: Path) -> None:
    """Fig 6: decision accuracy per method with Wilson 95% CIs (horizontal dot-and-whisker,
    one row per method), plus the ``no_retrieval`` floor and ``oracle`` ceiling as dashed
    horizontal reference lines. The paper's punchline figure: retrieval choice changes the LLM
    council's actual decision, not just a ranking metric."""
    methods = data["methods"]
    controls = data["controls"]
    y_pos = list(range(len(FIG6_ORDER)))[::-1]  # top-to-bottom in FIG6_ORDER

    fig, ax = plt.subplots(figsize=(3.3, 2.9))

    floor = controls["no_retrieval"]["mean"]
    ceiling = controls["oracle"]["mean"]
    ax.axvline(floor, color="#777777", lw=1.0, ls="--", zorder=1)
    ax.axvline(ceiling, color="#777777", lw=1.0, ls=":", zorder=1)
    # Labels sit in axes-fraction y (above every data row, regardless of ylim) so they can
    # never collide with the top method's dot/whiskers.
    ax.text(floor, 1.01, "no_retrieval\nfloor", ha="center", va="bottom", fontsize=5.8,
           color="#555555", transform=ax.get_xaxis_transform())
    ax.text(ceiling, 1.01, "oracle\nceiling", ha="center", va="bottom", fontsize=5.8,
           color="#555555", transform=ax.get_xaxis_transform())

    for y, name in zip(y_pos, FIG6_ORDER):
        row = methods[name]
        color = METHOD_COLORS[name]
        lo_err = row["mean"] - row["ci_lo"]
        hi_err = row["ci_hi"] - row["mean"]
        ax.errorbar([row["mean"]], [y], xerr=[[lo_err], [hi_err]], fmt="o", color=color,
                   ecolor=color, elinewidth=1.2, capsize=2.5, markersize=4.5, zorder=3)

    ax.set_yticks(y_pos)
    ax.set_yticklabels(FIG6_ORDER, fontsize=7.5)
    ax.set_ylim(-0.7, len(FIG6_ORDER) - 0.3)
    ax.set_xlim(-0.02, 1.02)
    ax.set_xlabel("decision accuracy (Wilson 95% CI)", fontsize=7.5)
    ax.tick_params(labelsize=7.0)
    ax.set_axisbelow(True)
    ax.grid(axis="x", color="#dddddd", lw=0.5, zorder=0)

    fig.tight_layout(pad=0.25)
    fig.savefig(out_stub.with_suffix(".pdf"), bbox_inches="tight")
    fig.savefig(out_stub.with_suffix(".png"), dpi=220, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=str, default=str(_FIGURES_DIR))
    ap.add_argument("--lambda-sweep", type=str,
                    default=str(_TCMF_PAPER_DIR / "results_lambda_sweep" /
                               "results_lambda_sweep.json"),
                    help="N10 Fig 4 data, produced by `python -m tcmfbench.run_lambda_sweep`")
    ap.add_argument("--mixed", type=str,
                    default=str(_TCMF_PAPER_DIR / "results_mixed" / "results_mixed.json"),
                    help="N11 Fig 5 edge-dropout data (small pool, matches tab:dropout), "
                         "produced by `python -m tcmfbench.run_mixed --n 300 --out results_mixed`")
    ap.add_argument("--spurious", type=str,
                    default=str(_TCMF_PAPER_DIR / "results_spurious" /
                               "results_spurious.json"),
                    help="N11 Fig 5 spurious-edge data, produced by "
                         "`python -m tcmfbench.run_spurious`")
    args = ap.parse_args()
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    data = build_fig1_scenario_json()
    scenario_path = out_dir / "fig1_scenario.json"
    scenario_path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")
    # Re-load before drawing: Fig 1 is provably drawn from the committed file, not from
    # whatever is still sitting in the `data` variable above.
    reloaded = json.loads(scenario_path.read_text())
    draw_fig1(reloaded, out_dir / "fig1_causal_graph")
    print(f"wrote {scenario_path}")
    print(f"wrote {out_dir / 'fig1_causal_graph.pdf'} / .png")

    draw_fig2(out_dir / "fig2_pipeline")
    print(f"wrote {out_dir / 'fig2_pipeline.pdf'} / .png")

    fig3_data = build_fig3_pairs_json()
    fig3_path = out_dir / "fig3_pairs.json"
    fig3_path.write_text(json.dumps(fig3_data, indent=2, sort_keys=True) + "\n")
    draw_fig3(json.loads(fig3_path.read_text()), out_dir / "fig3_theory")
    print(f"wrote {fig3_path}")
    print(f"wrote {out_dir / 'fig3_theory.pdf'} / .png")

    sweep_path = Path(args.lambda_sweep)
    if sweep_path.exists():
        sweep = json.loads(sweep_path.read_text())
        draw_fig4(sweep, out_dir / "fig4_recall_vs_lambda")
        print(f"wrote {out_dir / 'fig4_recall_vs_lambda.pdf'} / .png")
    else:
        print(f"SKIPPED Fig 4: {sweep_path} not found - run "
              "`python -m tcmfbench.run_lambda_sweep --n 300 --n-seeds 5 "
              "--out results_lambda_sweep` first")

    mixed_path, spurious_path = Path(args.mixed), Path(args.spurious)
    if mixed_path.exists() and spurious_path.exists():
        draw_fig5(json.loads(mixed_path.read_text(encoding="utf-8")),
                  json.loads(spurious_path.read_text(encoding="utf-8")),
                  out_dir / "fig5_degradation")
        print(f"wrote {out_dir / 'fig5_degradation.pdf'} / .png "
              f"(from {mixed_path}, {spurious_path})")
    else:
        print(f"SKIPPED Fig 5: {mixed_path} or {spurious_path} not found")

    fig6_data = build_fig6_data()
    fig6_path = out_dir / "fig6_data.json"
    fig6_path.write_text(json.dumps(fig6_data, indent=2, sort_keys=True) + "\n")
    reloaded6 = json.loads(fig6_path.read_text())
    draw_fig6(reloaded6, out_dir / "fig6_decision_accuracy")
    print(f"wrote {fig6_path}")
    print(f"wrote {out_dir / 'fig6_decision_accuracy.pdf'} / .png")


if __name__ == "__main__":
    main()
